import os
import subprocess

import config
import dockerapi as docker

FLAVOR = 'ubuntu'
DOCKER_CONF_FOLDER = '/etc/docker'
DNSMASQ_LOCAL_CONF = '/etc/NetworkManager/dnsmasq.d/01_docker'
DOCKER_BUILD_TARGET = 'base'


if not os.path.exists(DNSMASQ_LOCAL_CONF):
    DNSMASQ_LOCAL_CONF = DNSMASQ_LOCAL_CONF.replace('dnsmasq.d', 'conf.d')


def setup(tld=config.TOP_LEVEL_DOMAIN) -> int:
    return 0


def install(tld=config.TOP_LEVEL_DOMAIN) -> int:
    try:
        resolvconf = '/etc/resolv.conf'
        resolvconf_head = '/etc/resolvconf/resolv.conf.d/head'

        if not os.path.exists(resolvconf):
            content = '# Generated by docker-dns\n'
            open(resolvconf, 'w').write(content)

        dns = docker.NETWORK_GATEWAY
        resolvconf_new_lines = [
            f'nameserver {dns} #@docker-dns\n',
            'nameserver 1.1.1.1 #cloudflare #@docker-dns\n',
            'nameserver 8.8.8.8 #google #@docker-dns\n',
            'options timeout:1 #@docker-dns\n'
        ]
        if int(config.OS_VERSION.split('.')[0]) >= 18:
            resolvconf_head_lines = open(resolvconf_head, 'r').readlines()
            resolvconf_new_lines_filtered = [
                line for line in resolvconf_new_lines
                if line not in resolvconf_head_lines
            ]
            open(resolvconf_head, 'a').writelines(resolvconf_new_lines_filtered)
            subprocess.run(['resolvconf', '-u'])

        else:
            resolvconf_lines = open(resolvconf, 'r').readlines()
            resolvconf_new_lines_filtered = [line for line in resolvconf_new_lines if line not in resolvconf_lines]
            open(resolvconf, 'a').writelines(resolvconf_new_lines_filtered)

        return 0

    except FileNotFoundError:
        print('package "resolvconf" not installed, please install it with "sudo apt install resolvconf"')
        return 1


def uninstall(tld=config.TOP_LEVEL_DOMAIN) -> int:
    if os.path.exists(DNSMASQ_LOCAL_CONF):
        os.unlink(DNSMASQ_LOCAL_CONF)

    resolvconf_head = '/etc/resolvconf/resolv.conf.d/head'
    try:
        lines = open(resolvconf_head).readlines()
        original_lines = [line for line in lines if not line.endswith('docker-dns\n')]
        open(resolvconf_head, 'w').writelines(original_lines)
        subprocess.run(['resolvconf', '-u'])
        return 0

    except FileNotFoundError:
        return 1
